apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-lookup-service
  labels:
    app: account-lookup-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: account-lookup-service
  template:
    metadata:
      labels:
        app: account-lookup-service
    spec:
      containers:
      - name: account-lookup-service
        image: mojaloop/account-lookup-service:v11.3.0
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4001
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4001
        env:
          - name: ALS_SWITCH_ENDPOINT
            value: http://central-ledger:3001
          - name: ALS_DATABASE__HOST
            value: mysql-als
          - name: ALS_FEATURE_ENABLE_EXTENDED_PARTY_ID_TYPE
            value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: account-lookup-service-admin
spec:
  ports:
  - port: 4001
  selector:
    app: account-lookup-service
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: account-lookup-service
spec:
  ports:
  - port: 4002
  selector:
    app: account-lookup-service
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-lookup-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host: account-lookup-service.local
    http:
      paths:
      - path: /account-lookup-service-admin(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: account-lookup-service-admin
            port:
              number: 4001
      - path: /account-lookup-service(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: account-lookup-service-admin
            port:
              number: 4002
