apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-requests-service
  labels:
    app: transaction-requests-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # exeed the replicas by 1 pod
  selector:
    matchLabels:
      app: transaction-requests-service
  template:
    metadata:
      labels:
        app: transaction-requests-service
    spec:
      containers:
      - name: transaction-requests-service
        image: mojaloop/transaction-requests-service:v10.6.1.1-pisp
        livenessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4003
        readinessProbe:
          initialDelaySeconds: 30
          httpGet:
            path: /health
            port: 4003
        env:
          - name: ES_SWITCH_ENDPOINT
            value: http://central-ledger:3001

---
apiVersion: v1
kind: Service
metadata:
  name: transaction-requests-service
spec:
  ports:
  - port: 4003
  selector:
    app: transaction-requests-service
  clusterIP: None
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: transaction-requests-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: transaction-requests-service.local
      http:
        paths:
          - path: /transaction-requests-service(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: transaction-requests-service
                port:
                  number: 4003
